/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator_app;

/**
 *
 * @author Raffaele_Alfano (Wolfgang_87)
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    double num, ans;
    int calculation;
    
    public calculator() {
        initComponents();
        jOnButton.setEnabled(false);
    }
    
    public void arithmetic_operation()
    {
        switch(calculation)
        {
            case 1: //addition
                ans = num + Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
            case 2: //subtraction
                ans = num - Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
            case 3: //Multiplication
                ans = num * Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
            case 4: //division
                ans = num / Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void disable()
    {
        jOnButton.setEnabled(true);
        
        jTextField1.setEnabled(false);
        
        jNr0Button.setEnabled(false);
        jNr1Button.setEnabled(false);
        jNr2Button.setEnabled(false);
        jNr3Button.setEnabled(false);
        jNr4Button.setEnabled(false);
        jNr5Button.setEnabled(false);
        jNr6Button.setEnabled(false);
        jNr7Button.setEnabled(false);
        jNr8Button.setEnabled(false);
        jNr9Button.setEnabled(false);
        
        jFnClearButton.setEnabled(false);
        jFnDelButton.setEnabled(false);
        jFnDivButton.setEnabled(false);
        jFnEqualButton.setEnabled(false);
        jFnMinusButton.setEnabled(false);
        jFnMultButton.setEnabled(false);
        jFnPlusButton.setEnabled(false);
        jFnPointButton.setEnabled(false);
    }
    
    public void enable()
    {
        jTextField1.setEnabled(true);
        
        jNr0Button.setEnabled(true);
        jNr1Button.setEnabled(true);
        jNr2Button.setEnabled(true);
        jNr3Button.setEnabled(true);
        jNr4Button.setEnabled(true);
        jNr5Button.setEnabled(true);
        jNr6Button.setEnabled(true);
        jNr7Button.setEnabled(true);
        jNr8Button.setEnabled(true);
        jNr9Button.setEnabled(true);
        
        jFnClearButton.setEnabled(true);
        jFnDelButton.setEnabled(true);
        jFnDivButton.setEnabled(true);
        jFnEqualButton.setEnabled(true);
        jFnMinusButton.setEnabled(true);
        jFnMultButton.setEnabled(true);
        jFnPlusButton.setEnabled(true);
        jFnPointButton.setEnabled(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bGrSwitch = new javax.swing.ButtonGroup();
        jNr1Button = new javax.swing.JButton();
        jNr2Button = new javax.swing.JButton();
        jNr3Button = new javax.swing.JButton();
        jNr4Button = new javax.swing.JButton();
        jNr5Button = new javax.swing.JButton();
        jNr6Button = new javax.swing.JButton();
        jNr7Button = new javax.swing.JButton();
        jNr8Button = new javax.swing.JButton();
        jNr9Button = new javax.swing.JButton();
        jNr0Button = new javax.swing.JButton();
        jOnButton = new javax.swing.JRadioButton();
        jOffButton = new javax.swing.JRadioButton();
        jFnPlusButton = new javax.swing.JButton();
        jFnMinusButton = new javax.swing.JButton();
        jFnMultButton = new javax.swing.JButton();
        jFnDivButton = new javax.swing.JButton();
        jFnEqualButton = new javax.swing.JButton();
        jFnPointButton = new javax.swing.JButton();
        jFnClearButton = new javax.swing.JButton();
        jFnDelButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jStored = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(280, 453));
        setType(java.awt.Window.Type.UTILITY);

        jNr1Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr1Button.setText("1");
        jNr1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr1Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr1Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr1Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr1Button.setRolloverEnabled(false);
        jNr1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr1ButtonActionPerformed(evt);
            }
        });

        jNr2Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr2Button.setText("2");
        jNr2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr2Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr2Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr2Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr2Button.setRolloverEnabled(false);
        jNr2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr2ButtonActionPerformed(evt);
            }
        });

        jNr3Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr3Button.setText("3");
        jNr3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr3Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr3Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr3Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr3Button.setRolloverEnabled(false);
        jNr3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr3ButtonActionPerformed(evt);
            }
        });

        jNr4Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr4Button.setText("4");
        jNr4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr4Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr4Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr4Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr4Button.setRolloverEnabled(false);
        jNr4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr4ButtonActionPerformed(evt);
            }
        });

        jNr5Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr5Button.setText("5");
        jNr5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr5Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr5Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr5Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr5Button.setRolloverEnabled(false);
        jNr5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr5ButtonActionPerformed(evt);
            }
        });

        jNr6Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr6Button.setText("6");
        jNr6Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr6Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr6Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr6Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr6Button.setRolloverEnabled(false);
        jNr6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr6ButtonActionPerformed(evt);
            }
        });

        jNr7Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr7Button.setText("7");
        jNr7Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr7Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr7Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr7Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr7Button.setRolloverEnabled(false);
        jNr7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr7ButtonActionPerformed(evt);
            }
        });

        jNr8Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr8Button.setText("8");
        jNr8Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr8Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr8Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr8Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr8Button.setRolloverEnabled(false);
        jNr8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr8ButtonActionPerformed(evt);
            }
        });

        jNr9Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr9Button.setText("9");
        jNr9Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr9Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr9Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr9Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr9Button.setRolloverEnabled(false);
        jNr9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr9ButtonActionPerformed(evt);
            }
        });

        jNr0Button.setBackground(new java.awt.Color(153, 255, 255));
        jNr0Button.setText("0");
        jNr0Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNr0Button.setMaximumSize(new java.awt.Dimension(60, 37));
        jNr0Button.setMinimumSize(new java.awt.Dimension(60, 37));
        jNr0Button.setPreferredSize(new java.awt.Dimension(60, 37));
        jNr0Button.setRolloverEnabled(false);
        jNr0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNr0ButtonActionPerformed(evt);
            }
        });

        bGrSwitch.add(jOnButton);
        jOnButton.setText("On");
        jOnButton.setBorderPainted(true);
        jOnButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jOnButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jOnButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnButtonActionPerformed(evt);
            }
        });

        bGrSwitch.add(jOffButton);
        jOffButton.setText("Off");
        jOffButton.setBorderPainted(true);
        jOffButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jOffButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jOffButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOffButtonActionPerformed(evt);
            }
        });

        jFnPlusButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnPlusButton.setText("+");
        jFnPlusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnPlusButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnPlusButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnPlusButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnPlusButtonActionPerformed(evt);
            }
        });

        jFnMinusButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnMinusButton.setText("-");
        jFnMinusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnMinusButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnMinusButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnMinusButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnMinusButtonActionPerformed(evt);
            }
        });

        jFnMultButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnMultButton.setText("*");
        jFnMultButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnMultButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnMultButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnMultButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnMultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnMultButtonActionPerformed(evt);
            }
        });

        jFnDivButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnDivButton.setText("/");
        jFnDivButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnDivButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnDivButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnDivButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnDivButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnDivButtonActionPerformed(evt);
            }
        });

        jFnEqualButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnEqualButton.setText("=");
        jFnEqualButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnEqualButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnEqualButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnEqualButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnEqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnEqualButtonActionPerformed(evt);
            }
        });

        jFnPointButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnPointButton.setText(".");
        jFnPointButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnPointButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnPointButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnPointButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnPointButtonActionPerformed(evt);
            }
        });

        jFnClearButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnClearButton.setText("C");
        jFnClearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnClearButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnClearButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnClearButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnClearButtonActionPerformed(evt);
            }
        });

        jFnDelButton.setBackground(new java.awt.Color(153, 255, 0));
        jFnDelButton.setText("<-");
        jFnDelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFnDelButton.setMaximumSize(new java.awt.Dimension(60, 37));
        jFnDelButton.setMinimumSize(new java.awt.Dimension(60, 37));
        jFnDelButton.setPreferredSize(new java.awt.Dimension(60, 37));
        jFnDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnDelButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jStored.setForeground(new java.awt.Color(255, 153, 153));
        jStored.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jStored.setText("1+");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField1)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(jNr4Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jNr5Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jNr6Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jFnMinusButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(layout.createSequentialGroup()
                                    .add(jNr0Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jFnPointButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jFnEqualButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jFnDivButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jNr7Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jOffButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(jOnButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jFnDelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jFnClearButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(jNr8Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jNr9Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jFnPlusButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jNr1Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jNr2Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jNr3Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFnMultButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jStored, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jStored, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jOnButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jOffButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnDelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnClearButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNr9Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr8Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr7Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnPlusButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNr6Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr5Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr4Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnMinusButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNr3Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr2Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jNr1Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnMultButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNr0Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnDivButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnEqualButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFnPointButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jNr0ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"0");
    }                                          

    private void jNr1ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"1");
    }                                          

    private void jNr2ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"2");
    }                                          

    private void jNr3ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"3");
    }                                          

    private void jNr4ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"4");
    }                                          

    private void jNr5ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"5");
    }                                          

    private void jNr6ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"6");
    }                                          

    private void jNr7ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"7");
    }                                          

    private void jNr8ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"8");
    }                                          

    private void jNr9ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText(jTextField1.getText()+"9");
    }                                          

    private void jFnPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        num = Double.parseDouble(jTextField1.getText());
        calculation = 1;
        jTextField1.setText("");
        jStored.setText(num + "+");
    }                                             

    private void jFnMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        num = Double.parseDouble(jTextField1.getText());
        calculation = 2;
        jTextField1.setText("");
        jStored.setText(num + "-");
    }                                              

    private void jFnMultButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        num = Double.parseDouble(jTextField1.getText());
        calculation = 3;
        jTextField1.setText("");
        jStored.setText(num + "*");
    }                                             

    private void jFnDivButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        num = Double.parseDouble(jTextField1.getText());
        calculation = 1;
        jTextField1.setText("");
        jStored.setText(num + "/");
    }                                            

    private void jFnPointButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        jTextField1.setText(jTextField1.getText()+".");// TODO add your handling code here:
    }                                              

    private void jFnClearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        jTextField1.setText("");
    }                                              

    private void jFnDelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int length = jTextField1.getText().length();
        int prevLength = jTextField1.getText().length()-1;
        String store;
        if(length>0)
        {
            StringBuilder back = new StringBuilder(jTextField1.getText());
            back.deleteCharAt(prevLength);
            store= back.toString();
            jTextField1.setText(store);
        }
    }                                            

    private void jFnEqualButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        arithmetic_operation();
        jStored.setText("");
    }                                              

    private void jOffButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        disable();
    }                                          

    private void jOnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        enable();
    }                                         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup bGrSwitch;
    private javax.swing.JButton jFnClearButton;
    private javax.swing.JButton jFnDelButton;
    private javax.swing.JButton jFnDivButton;
    private javax.swing.JButton jFnEqualButton;
    private javax.swing.JButton jFnMinusButton;
    private javax.swing.JButton jFnMultButton;
    private javax.swing.JButton jFnPlusButton;
    private javax.swing.JButton jFnPointButton;
    private javax.swing.JButton jNr0Button;
    private javax.swing.JButton jNr1Button;
    private javax.swing.JButton jNr2Button;
    private javax.swing.JButton jNr3Button;
    private javax.swing.JButton jNr4Button;
    private javax.swing.JButton jNr5Button;
    private javax.swing.JButton jNr6Button;
    private javax.swing.JButton jNr7Button;
    private javax.swing.JButton jNr8Button;
    private javax.swing.JButton jNr9Button;
    private javax.swing.JRadioButton jOffButton;
    private javax.swing.JRadioButton jOnButton;
    private javax.swing.JLabel jStored;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
